@startuml

title __ADMIN's Class Diagram__\n

  namespace main {
    namespace admin {
      class main.admin.AddUserController {
          + firstName : TextField
          + lastName : TextField
          + password : PasswordField
          + patronymic : TextField
          + position : TextField
          - root : ComboBox<String>
          - username : TextField
          + aboutUs()
          + addNew()
          + cancel()
          + initialize()
          + passwordValue()
          + toBack()
          + toHome()
          + usernameValue()
      }
    }
  }
  

  namespace main {
    namespace admin {
      class main.admin.RefactorUserController {
          + firstName : TextField
          + lastName : TextField
          + password : PasswordField
          + patronymic : TextField
          + position : TextField
          + root : ComboBox<String>
          + username : TextField
          + aboutUs()
          + cancel()
          + changeAdmin()
          + changeFirstName()
          + changeLastName()
          + changePassword()
          + changePatronymic()
          + changePosition()
          + changeUsername()
          + delete()
          + initialize()
          + passwordValue()
          + toBack()
          + toHome()
          + usernameValue()
      }
    }
  }
  

  namespace main {
    namespace admin {
      class main.admin.UserListController {
          - filteredData : FilteredList<User>
          - full_name : TableColumn<User, String>
          - login : TableColumn<User, String>
          - menu : MenuBar
          - position : TableColumn<User, String>
          - search : TextField
          - table : TableView<User>
          + addNew()
          + clickRow()
          + find()
          + initialize()
          - aboutUs()
          - logout()
          - toHome()
          - toProfile()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
