@startuml

title __CHOICES's Class Diagram__\n

  namespace choices {
    class choices.ClientChoices {
        {static} + DISABILITY_GROUP : ObservableList<String>
        {static} + EDUCATION : ObservableList<String>
        {static} + LEVEL : ObservableList<String>
        {static} + LOCATION : ObservableList<String>
        {static} + MARITAL_STATUS : ObservableList<String>
        {static} + REGISTRATION : ObservableList<String>
        {static} + SECURITY : ObservableList<String>
        {static} + SEX : ObservableList<String>
        {static} + SPECIAL_SOCIAL_STATUS : ObservableList<String>
        {static} + TYPE : ObservableList<String>
        {static} + WORK_PLACE : ObservableList<String>
        {static} + YESNO : ObservableList<String>
    }
  }
  

  namespace choices {
    class choices.FieldControl {
        - choices : ObservableList<String>
        - control : Control
        - name : String
        - rusName : String
        + FieldControl()
        + getChoices()
        + getControl()
        + getName()
        + getRusName()
        + setControl()
        + toString()
    }
  }
  

  namespace choices {
    class choices.FieldControlBoyko {
        - choices : List<String>
        - name : String
        - rusName : String
        - toggleGroup : ToggleGroup
        + FieldControlBoyko()
        + getChoices()
        + getName()
        + getRusName()
        + getToggleGroup()
        + setToggleGroup()
    }
  }
  

  namespace choices {
    class choices.FieldControlGAGE {
        - control : Control
        - name : String
        - rusName : String
        - toggleGroup : ToggleGroup
        + FieldControlGAGE()
        + getChoices()
        + getControl()
        + getName()
        + getRusName()
        + getToggleGroup()
        + setControl()
        + setToggleGroup()
    }
  }
  

  namespace choices {
    class choices.InterTestBoykoChoices {
        {static} + AGGRESS : List<String>
        {static} + ALARM : List<String>
        {static} + CHILD_PARENT : List<String>
        {static} + CRITICISM : List<String>
        {static} + FAMILY_RELATION : List<String>
        {static} + FRIENDS : List<String>
        {static} + LEISURE : List<String>
        {static} + MEMORY_DISORDER : List<String>
        {static} + OVERALL_ASSESSMENT : List<String>
        {static} + SELF_SERVICE : List<String>
        {static} + WORK_ACTIVITY : List<String>
    }
  }
  

  namespace choices {
    class choices.Question {
        - names : List<String>
        - values : List<Integer>
        + Question()
        + getName()
        + getNames()
        + getValue()
        + getValues()
        + toString()
    }
  }
  

  namespace choices {
    class choices.TestBoykoChoices {
        {static} + AGGRESS : List<String>
        {static} + ALARM : List<String>
        {static} + CHILD_PARENT : List<String>
        {static} + CRITICISM : List<String>
        {static} + FAMILY_RELATION : List<String>
        {static} + FRIENDS : List<String>
        {static} + LEISURE : List<String>
        {static} + MEMORY_DISORDER : List<String>
        {static} + SELF_SERVICE : List<String>
        {static} + WORK_ACTIVITY : List<String>
    }
  }
  

  namespace choices {
    class choices.TestGAGEChoices {
        {static} + COMPANY : Question
        {static} + DO_NOT_WORK_WHEN : Question
        {static} + DRINK_ALCOHOL_TIME : Question
        {static} + HOW_USE : Question
        {static} + INJURIES : Question
        {static} + LOSS_DOCUMENTS_TIME : Question
        {static} + LOSS_DOCUMENTS_WHEN : Question
        {static} + LOTS_ALCOHOL_TIME : Question
        {static} + NOYES : Question
        {static} + POOR_HEALTH : Question
        {static} + SUBSTANCES : Question
        {static} + TRY_SUBSTANCES : Question
    }
  }
  

  choices.FieldControlGAGE o-- choices.Question : choices


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
